import type { Metadata } from "next";
import "./globals.css";

import { inter, lexendDeca } from "@/app/fonts";
import clsxm from "@/common/libs/clsxm";
import dynamic from "next/dynamic";

const NextProgress = dynamic(
  () => import("@/common/components/next-progress"),
  {
    ssr: false,
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsxm(inter.variable, lexendDeca.variable, "font-inter")}
      >
        {children}
      </body>
    </html>
  );
}
